
package ubersuccess;

import java.util.List;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class GUI extends javax.swing.JFrame {

    public GUI() {
        initComponents();
        
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                // do some actions here, for example
                // print first column value from selected row
                 if (!event.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) 
                 {
                    System.out.println(jTable1.getValueAt(
                            jTable1.getSelectedRow(), 0).toString());
                    List<Car> fleet = fleetManager.getCarWithSerial6(
                            jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
                    Car c=fleet.get(0);
                    make.setText(c.make);
                    manyear.setText(c.manYear+"");
                    numSeats.setText(c.numSeats+"");
                    serialNumber.setText(c.serialNumber);
                    modelNumber.setText(c.modelNumber);
                    city.setText(c.city);
                    available.setSelected(c.isAvailable);
                    Maintenance.setSelected(c.mainCertExpired);
                    
                            
                 }
            }
        });
    }
    
    public FleetManager fleetManager=new FleetManager();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonImport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        makeFilter = new javax.swing.JTextField();
        maxFilter = new javax.swing.JTextField();
        minFilter = new javax.swing.JTextField();
        yearFilter1 = new javax.swing.JTextField();
        serialFilter1 = new javax.swing.JTextField();
        carsAvailable = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        cityFilter = new javax.swing.JTextField();
        modifiedDt = new javax.swing.JLabel();
        modelFilter = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        manufacturers = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        make = new javax.swing.JTextField();
        manyear = new javax.swing.JTextField();
        numSeats = new javax.swing.JTextField();
        serialNumber = new javax.swing.JTextField();
        modelNumber = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        available = new javax.swing.JCheckBox();
        jButtonEdit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Maintenancebox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 590, 340));

        jButtonImport.setText("Import");
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Uber Car Fleet Manager");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 780, 280));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("1.find first available car");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, -1));

        jButton2.setText("2. how many cars are currently available");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 320, -1));

        jButton3.setText("3. list all cars that are made by toyota, gm, etc");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 310, -1));

        jButton4.setText("4. list all cars that are manu in year ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 310, -1));

        jButton5.setText("5. list all cars with min x seats and max y seats ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 310, -1));

        jButton6.setText("6. find the car with the given serial num");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 300, -1));

        makeFilter.setText("gm");
        jPanel1.add(makeFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, -1));

        maxFilter.setText("9");
        jPanel1.add(maxFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 40, -1));

        minFilter.setText("2");
        jPanel1.add(minFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 30, -1));

        yearFilter1.setText("2018");
        jPanel1.add(yearFilter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, -1));

        serialFilter1.setText("4444444444");
        jPanel1.add(serialFilter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, -1));

        carsAvailable.setText("0");
        jPanel1.add(carsAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 30, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 410, 340));

        jLabel2.setText("Search Functions");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 380, -1, -1));

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setText("7. list all cars given the model num");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 280, -1));

        jButton8.setText("8. list all manufacturers");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, -1));

        jButton9.setText("9. when was the last time fleet catalog was updated");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 330, -1));

        jButton10.setText("10. list all cars in given city");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 190, -1));

        cityFilter.setText("boston");
        jPanel2.add(cityFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, -1));

        modifiedDt.setText("2018");
        jPanel2.add(modifiedDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 30, -1));

        modelFilter.setText("9876");
        jPanel2.add(modelFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        jButton12.setText("11. list all cars that expired maintenance certis");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 370, -1));

        manufacturers.setText("manufacturers");
        jPanel2.add(manufacturers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 400, 400, 340));

        jLabel3.setText("Search Functions");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, -1));

        make.setText("ford");
        make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeActionPerformed(evt);
            }
        });
        jPanel3.add(make, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, -1));

        manyear.setText("2020");
        jPanel3.add(manyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 70, -1));

        numSeats.setText("5");
        jPanel3.add(numSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, -1));

        serialNumber.setText("78787878");
        jPanel3.add(serialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        modelNumber.setText("786");
        jPanel3.add(modelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 60, -1));

        city.setText("boston");
        jPanel3.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 100, -1));

        available.setSelected(true);
        available.setText("Available ?");
        available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableActionPerformed(evt);
            }
        });
        jPanel3.add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jButtonEdit.setText("Update");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 90, -1));

        jLabel4.setText("Make");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel5.setText("Year of manufacturing");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel6.setText("Number of Seats");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel7.setText("Serial Number");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel8.setText("Model Number");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel9.setText("City");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        Maintenancebox.setText("Maintenance");
        Maintenancebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenanceboxActionPerformed(evt);
            }
        });
        jPanel3.add(Maintenancebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 120, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 630, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refreshTable(fleetManager.getFirstAvailableCar1(),true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        carsAvailable.setText(fleetManager.getNumCars2()+"");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        refreshTable(fleetManager.getCarsManBy3(makeFilter.getText()),true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                refreshTable(
                                fleetManager.getCarsManInYear4(
                                        Integer.parseInt(yearFilter1.getText())),true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                refreshTable(
                        fleetManager.getCarsMinMaxSeats5(
                                Integer.parseInt(minFilter.getText())
                                , Integer.parseInt(maxFilter.getText())),true);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                refreshTable(fleetManager.getCarWithSerial6(
                    serialFilter1.getText()),true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        refreshTable(fleetManager.getCarsByModel7(modelFilter.getText()),true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Set<String> manus = fleetManager.getAllManus8();
        manufacturers.setText("");
        String allmanu="";
        for(String m : manus)
            allmanu+=(","+m);
        manufacturers.setText(allmanu);                    
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
//                        jTable1.setModel(
//                new DefaultTableModel(
//                        fleetManager.getArray(
//                                fleetManager.getLastModified9()), 
//                        fleetManager.getColumns()));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                refreshTable(
                        fleetManager.getAllCarsInCity10(
                                cityFilter.getText()),true);
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String m = make.getText();
        if(m.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter car make/manufacturer", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        String y=manyear.getText();
        if(y.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter year of manufacturing", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        String sts=numSeats.getText();
        if(sts.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter number of seats", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        String sn=serialNumber.getText();
        if(sn.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter serial number", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        // check for duplicate serial
        if(fleetManager.isExistsSerialNumber(sn))
        {
            JOptionPane.showMessageDialog(null, 
                    "Serial number already Exists!", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        String mn=modelNumber.getText();
        if(mn.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter model number", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        String c=city.getText();
        if(c.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter city", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }        
        fleetManager.addCar(
            new Car(
                    m,
                    Integer.parseInt(y), 
                    Integer.parseInt(sts),
                    sn,
                    mn,
                    c, 
                    true,
                    available.isSelected()
            ));
        refreshTable(fleetManager.carFleet, false);

        jTable2.setModel(new DefaultTableModel(fleetManager.getArray(), 
                fleetManager.getColumns()));

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed

        JFileChooser fc=new JFileChooser("c:/");
        fc.showOpenDialog(null);
        String path=fc.getSelectedFile().getAbsolutePath();
        fleetManager.importDataFromCSV(path);
        dtm=new DefaultTableModel(
                        fleetManager.getArray(), 
                        fleetManager.getColumns());
        jTable1.setModel(dtm);
        jTable2.setModel(new DefaultTableModel(fleetManager.getArray(), 
                        fleetManager.getColumns()));
    }//GEN-LAST:event_jButtonImportActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
                refreshTable(
                        fleetManager.getAllCarsThatExpired11()
                                ,true);
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed

        String m = make.getText();
        if(m.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter car make/manufacturer", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        String y=manyear.getText();
        if(y.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter year of manufacturing", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        String sts=numSeats.getText();
        if(sts.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter number of seats", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        String sn=serialNumber.getText();
        if(sn.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter serial number", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        String mn=modelNumber.getText();
        if(mn.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter model number", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        String c=city.getText();
        if(c.equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Please enter city", "Warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }        
        
        Car car = fleetManager.getCarWithSerial(
                serialNumber.getText());
        car.make=m;
        car.manYear=Integer.parseInt(manyear.getText());
        car.modelNumber=mn;
        car.numSeats=Integer.parseInt(numSeats.getText());
        car.city=c;
        car.isAvailable=available.isSelected();
        car.mainCertExpired=Maintenance.isSelected();
//        make.setText(c.make);
//        manyear.setText(c.manYear+"");
//        numSeats.setText(c.numSeats+"");
//        serialNumber.setText(c.serialNumber);
//        modelNumber.setText(c.modelNumber);
//        city.setText(c.city);
//        available.setSelected(c.isAvailable);

        
//        fleetManager.addCar(
//            new Car(
//                    m,
//                    Integer.parseInt(y), 
//                    Integer.parseInt(sts),
//                    sn,
//                    mn,
//                    c, 
//                    true,
//                    available.isSelected()
//            ));

        //fleetManager.carFleet.get(0).manYear=2022;
        refreshTable(fleetManager.carFleet, false);

        jTable2.setModel(new DefaultTableModel(fleetManager.getArray(), 
                fleetManager.getColumns()));

    }//GEN-LAST:event_jButtonEditActionPerformed

    private void makeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeActionPerformed

    private void availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableActionPerformed

    private void MaintenanceboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenanceboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaintenanceboxActionPerformed

    DefaultTableModel dtm=new DefaultTableModel();
    public void refreshTable(List<Car>fleet, boolean clear)
    {
        //if(clear)
        //        fleetManager.carFleet.clear();

        //jTable1=new JTable();
        //this.add(jTable1);
        //jTable1.setModel(new DefaultTableModel());
        //dtm=(DefaultTableModel)jTable1.getModel();
        //dtm.setRowCount(0);
        //dtm.getDataVector().removeAllElements();
        //dtm.fireTableDataChanged();
        //jTable1.setModel(dtm);
//        while (dtm.getRowCount()>0)
//          {
//             dtm.removeRow(0);
//          }
        dtm.setDataVector(fleetManager.getArray(fleet), 
                fleetManager.getColumns());
        //jTable1.setModel(dtm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Maintenancebox;
    private javax.swing.JCheckBox available;
    private javax.swing.JLabel carsAvailable;
    private javax.swing.JTextField city;
    private javax.swing.JTextField cityFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField make;
    private javax.swing.JTextField makeFilter;
    private javax.swing.JLabel manufacturers;
    private javax.swing.JTextField manyear;
    private javax.swing.JTextField maxFilter;
    private javax.swing.JTextField minFilter;
    private javax.swing.JTextField modelFilter;
    private javax.swing.JTextField modelNumber;
    private javax.swing.JLabel modifiedDt;
    private javax.swing.JTextField numSeats;
    private javax.swing.JTextField serialFilter1;
    private javax.swing.JTextField serialNumber;
    private javax.swing.JTextField yearFilter1;
    // End of variables declaration//GEN-END:variables

    private static class Maintenance {

        private static void setSelected(boolean mainCertExpired) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static boolean isSelected() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public Maintenance() {
        }
    }
}
